apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  labels:
    app: nginx-example
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: nginx-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
      - name: nginx
        image: nginx:latest
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-example
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: nginx-example
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-example
            port:
              number: 80